config/routes.rb
GS1::Application.routes.draw do
  
  get "gerencia/index"
  get "cargo/index"
  get "perfil/index"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :usuarios 

  resources :productos do #/empresas/1/productos

      collection do
        put 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
      end
    end

  
  
  resources :glns do
      collection do
        delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
      end

  end

  resources :empresas do  

    resources :empresa_servicios
    resources :etiquetas do
      collection do
        get 'exportar', :action => 'exportar', :as => 'exportar' 
      end
    end
    
    resources :productos do #/empresas/1/productos

      collection do
        put 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
        
      end
    end

    resources :glns do
      collection do
        delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
      end

    end

    resources :datos_contactos   #/empresas/1/datos_contactos
    
    collection do
      put 'update_multiple', :action => 'update_multiple', :as => 'update_multiple' # La ruta update_multiple para empresas
    end
  end
  
 
  resources :ciudades
  resources :clasificaciones
  resources :municipios
  resources :sessions

  root :to => 'sessions#new'

end

app/models/datos_contacto.rb
class DatosContacto < ActiveRecord::Base
  attr_accessible :cargo_contacto, :contacto, :nombre_contacto, :prefijo, :tipo, :datos_contacto
  self.table_name = 'empresa_contacto'
  validates :contacto, :tipo,  :presence => {:message => "No puede estar en blanco"}, :on => :create
  #validates :contacto, format: { with: /^[0-9]\d*$/, on: :create, :message => "Solo numeros para el contacto"} # Validacion al crear
  belongs_to :empresa


  def self.modificar_etiqueta(parametros)

  	contacto = DatosContacto.find(:first, :conditions => ["prefijo = ? and tipo = ?", parametros[:empresa_id], 'telefono'])
  	contacto.contacto = parametros[:contacto]
  	contacto.save

    empresa = Empresa.find(:first, :conditions => ["prefijo = ?", parametros[:empresa_id]])
    empresa.rep_legal = parametros[:nombre_contacto]
    empresa.cargo_rep_legal = parametros[:cargo_contacto]
    empresa.save
  end

end

app/controllers/datos_contactos_controller.rb
class DatosContactosController < ApplicationController
  before_filter :require_authentication
  # GET /datos_contactos
  # GET /datos_contactos.json
  def index

    
    @datos_contactos = DatosContacto.find(:all, :conditions => ["prefijo =?", params[:empresa_id]])
    @empresa = Empresa.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]])
    @navegabilidad = @empresa.nombre_empresa + " > Datos de contacto"
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @datos_contactos }
    end
  end

  # GET /datos_contactos/1
  # GET /datos_contactos/1.json
  def show
    
    @datos_contacto = DatosContacto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @datos_contacto }
    end
  end

  # GET /datos_contactos/new
  # GET /datos_contactos/new.json
  def new


    @empresa = Empresa.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]])
    @datos_contacto = @empresa.datos_contacto.build  ## Crea  el formulario para los datos_contacto
    @navegabilidad = @empresa.nombre_empresa + " > Crear contacto"
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @datos_contacto }
    end
  end

  # GET /datos_contactos/1/edit
  def edit
    @empresa = Empresa.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]])
    @datos_contacto = DatosContacto.find(params[:id])
    @navegabilidad = @empresa.nombre_empresa + " > Editar contacto"
  end

  # POST /datos_contactos
  # POST /datos_contactos.json
  def create

    @empresa = Empresa.find(:first, :conditions =>["prefijo = ?", params[:empresa_id]])
    @datos_contacto = @empresa.datos_contacto.build(params[:datos_contacto])
    @datos_contacto = DatosContacto.new(params[:datos_contacto])

    respond_to do |format|
      if @datos_contacto.save
        format.html { redirect_to "/empresas/#{params[:empresa_id]}/edit?editar=true#data_table_empresas_datos_contacto", notice: "El contacto fue agregado exitosamente."}        
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /datos_contactos/1
  # PUT /datos_contactos/1.json
  def update
    
    @datos_contacto = DatosContacto.find(params[:id])

    respond_to do |format|
      if @datos_contacto.update_attributes(params[:datos_contacto])
        format.html { redirect_to "/empresas/#{params[:empresa_id]}/edit?editar=true##data_table_empresas_datos_contacto", notice: "El contacto fue editado exitosamente."}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @datos_contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datos_contactos/1
  
  def destroy
    
    @datos_contacto = DatosContacto.find(params[:id])
    @datos_contacto.destroy

    respond_to do |format|
      format.html { redirect_to "/empresas/#{params[:empresa_id]}#data_table_empresas_datos_contacto", notice: "Contacto eliminado."}
    end
  end
end

app/views/datos_contactos/_form.html.haml
%section.contexto
  %label.contexto=@navegabilidad
  %hr.contexto{:size => "1"}
  = form_for [@empresa, @datos_contacto], :html => {:id => "formulario_datos_contacto"} do |f|
    - if @datos_contacto.errors.any?
      #error_explanation
        %h2= "#{pluralize(@datos_contacto.errors.count, "error")} prohibited this datos_contacto from being saved:"
        %ul
          - @datos_contacto.errors.full_messages.each do |msg|
            %li= msg

    %table
      %tr
        %td
          Prefijo
        %td
          = f.text_field :prefijo, :readonly => :true, :class => "campo_readonly"
      %tr
        %td    
          Tipo Contacto
        %td          
          = f.select(:tipo, options_for_select(['email', 'fax', 'opcional', 'telefono', 'secundario'], @datos_contacto.tipo))
      %tr
        %td
          Detalle
        %td
          = f.text_field :contacto
      
    .actions

      %button#submit.ui-state-default.ui-corner-all.guardar_contacto{:type => "submit", :title => "Guardar cambios del contacto"}
        %span.ui-icon.ui-icon-disk
        Guardar
      

      %a.ui-state-default.ui-corner-all.nuevo_contacto{:href => "javascript:window.history.back()", :title => "Regresar a los datos de la empresa"}
        %span.ui-icon.ui-icon-arrowreturnthick-1-w
        Regresar

app/views/datos_contactos/edit.html.haml
= render 'form'

app/views/datos_contactos/index.html.haml
%section.contexto
  %label.contexto=@navegabilidad 
  %hr.contexto{:size => "1"}
%section#areaTrabajo.areaTrabajo
  %table#data_table_empresas_datos_contacto.display
    %thead
      %tr
        
        %th Tipo Contacto
        %th Contacto
       
        %th Editar contacto
        %th Eliminar contacto
    %tbody
      - @datos_contactos.each do |datos_contacto|
        %tr
        
          %td= datos_contacto.tipo
          %td= datos_contacto.contacto
         
          %td= link_to(( content_tag(:span, '',:class => 'ui-icon ui-icon-extlink')+'Editar').html_safe,  "/empresas/#{params[:empresa_id]}/datos_contactos/#{datos_contacto.id})/edit",{:class => "ui-state-default ui-corner-all botones_servicio", :title => "Editar contacto #{datos_contacto.nombre_contacto}"})
          %td= link_to(( content_tag(:span, '',:class => 'ui-icon ui-icon-extlink')+'Eliminar').html_safe, "/empresas/#{params[:empresa_id]}/datos_contactos/#{datos_contacto.id}", {:method => :delete, :data => { :confirm => 'Seguro ELIMINAR este contacto?'}, :class => "ui-state-default ui-corner-all botones_servicio", :title => "Eliminar contacto #{datos_contacto.nombre_contacto}" }) 
              
  %br/
  %br/
  %a.ui-state-default.ui-corner-all.nuevo_contacto{:href => "#{new_empresa_datos_contacto_path}", :title => "Agregar un nuevo contacto para la empresa #{@empresa.nombre_empresa}"}
    %span.ui-icon.ui-icon-circle-plus
    Nuevo Contacto

  %a.ui-state-default.ui-corner-all.regresar_editar_empresa{:href => "javascript:window.history.back()", :title => "Regresar"}
    %span.ui-icon.ui-icon-arrowreturnthick-1-w
    Regresar

  

app/views/datos_contactos/new.html.haml
%h1 New datos_contacto

= render 'form'

app/views/datos_contactos/show.html.haml
%p#notice= notice

%p
  %b Prefijo:
  = @datos_contacto.prefijo
%p
  %b Contacto:
  = @datos_contacto.contacto
%p
  %b Tipo:
  = @datos_contacto.tipo
%p
  %b Nombre contacto:
  = @datos_contacto.nombre_contacto
%p
  %b Cargo contacto:
  = @datos_contacto.cargo_contacto

= link_to 'Edit', edit_datos_contacto_path(@datos_contacto)
\|
= link_to 'Back', datos_contactos_path