config/routes.rb
GS1::Application.routes.draw do
  
  get "gerencia/index"
  get "cargo/index"
  get "perfil/index"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :usuarios 

  resources :productos do #/empresas/1/productos

      collection do
        put 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
      end
    end

  
  
  resources :glns do
      collection do
        delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
      end

  end

  resources :empresas do  

    resources :empresa_servicios
    resources :etiquetas do
      collection do
        get 'exportar', :action => 'exportar', :as => 'exportar' 
      end
    end
    
    resources :productos do #/empresas/1/productos

      collection do
        put 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
        
      end
    end

    resources :glns do
      collection do
        delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
      end

    end

    resources :datos_contactos   #/empresas/1/datos_contactos
    
    collection do
      put 'update_multiple', :action => 'update_multiple', :as => 'update_multiple' # La ruta update_multiple para empresas
    end
  end
  
 
  resources :ciudades
  resources :clasificaciones
  resources :municipios
  resources :sessions

  root :to => 'sessions#new'

end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_filter :require_authentication
  # GET /productos
  # GET /productos.json
  
  prawnto :prawn => { :top_margin => 10} 

  def index
    

    productos = Producto.where("productos_empresa.prefijo = ?", params[:empresa_id]).includes({:productos_empresa => :empresa}, :estatus, :tipo_gtin).order("productos.fecha_inscripcion") 
    @empresa = Empresa.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]])
    @empresa = EmpresaEliminada.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]]) if @empresa.nil?

    respond_to do |format|
      format.html {
                    if params[:retirar]
                      @navegabilidad = @empresa.nombre_empresa + " > Retirar Productos" 
                      render :template =>'/productos/retirar_productos.html.haml'
                    elsif params[:retirados]
                      @navegabilidad = @empresa.nombre_empresa + " > Productos Retirados"
                      render :template =>'/productos/productos_retirados.html.haml'
                    elsif params[:eliminar]
                      @navegabilidad = @empresa.nombre_empresa + "> Productos Retirados > Eliminar Productos"
                      render :template =>'/productos/eliminar_productos.html.haml'
                    elsif params[:eliminados]
                      @empresa = Empresa.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]])
                      @empresa = @empresa ?  @empresa : EmpresaEliminada.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]])
                      @navegabilidad = @empresa.nombre_empresa + " > Productos Eliminados"
                      render :template =>'/productos/productos_eliminados.html.haml'
                    else
                      @navegabilidad = @empresa.nombre_empresa + " > Productos Activos > Listado"
                      render :template =>'/productos/index.html.haml'

                    end
                  }
      format.json { 
                    
                    if params[:retirar]
                      render json: (RetirarProductosDatatable.new(view_context))
                    elsif params[:gtin]
                      gtin = params[:gtin]
                      digito_verificacion = Producto.calcular_digito_verificacion(params[:gtin].to_i,"GTIN-13")
                      codigo_generado =  gtin + digito_verificacion.to_s
                      producto = ProductosEmpresa.find(:first, :conditions => ["prefijo = ? and gtin = ?", params[:prefijo], codigo_generado])
                      render json: producto
                    elsif params[:retirados]
                      render json: (ProductosRetiradosDatatable.new(view_context))
                    elsif params[:eliminar]
                      render json: (EliminarProductosDatatable.new(view_context))
                    elsif params[:eliminados]
                      render json: (ProductosEliminadosDatatable.new(view_context))
                    else
                      if UsuariosAlcance.verificar_alcance(session[:perfil], 'Modificar Producto')
                        render json: ProductosDatatable.new(view_context) 
                      else
                        render json: ProductosNotEditableDatatable.new(view_context) 
                      end
                    end
                  }
      format.pdf  {
                    if params[:retirar]
                      @productos = Producto.where("productos_empresa.prefijo = ? and estatus.descripcion = ?", params[:empresa_id], 'Activo').includes({:productos_empresa => :empresa}, :estatus, :tipo_gtin).order("producto.fecha_creacion") 
                      render '/productos/retirar_productos.pdf.prawn'
                    elsif params[:retirados]
                      @productos = Producto.where("productos_empresa.prefijo = ? and estatus.descripcion like ? and estatus.alcance like ?",params[:empresa_id], 'Retirado', 'Producto').includes({:productos_empresa => :empresa}, :estatus, :tipo_gtin, {:productos_retirados => :sub_estatus}, {:productos_retirados => :motivo_retiro})
                      render '/productos/productos_retirados.pdf.prawn'
                    elsif params[:eliminar]
                      @productos = Producto.where("productos_empresa.prefijo = ? and estatus.descripcion like ? and estatus.alcance like ?",params[:empresa_id], 'Retirado', 'Producto').includes({:productos_empresa => :empresa}, :estatus, :tipo_gtin, {:productos_retirados => :sub_estatus}, {:productos_retirados => :motivo_retiro})
                      render '/productos/eliminar_productos.pdf.prawn'
                    elsif params[:eliminados]
                      @productos = ProductoEliminado.where("productos_empresa.prefijo = ? and estatus.descripcion like ? and estatus.alcance like ?", params[:empresa_id], 'Eliminado', 'Producto').includes(:estatus, :tipo_gtin, {:producto_elim_detalle => :sub_estatus}, {:producto_elim_detalle => :motivo_retiro}, {:productos_empresa => :empresa})
                      render '/productos/productos_eliminados.pdf.prawn'
                    else
                      @productos = Producto.where("productos_empresa.prefijo = ? and estatus.descripcion = ?", params[:empresa_id], 'Activo').includes({:productos_empresa => :empresa}, :estatus, :tipo_gtin).order("producto.fecha_creacion") 
                      render '/productos/index.pdf.prawn'
                    end
      }
      format.xlsx{
                  if params[:retirar]
                    @productos = Producto.where("productos_empresa.prefijo = ?", params[:empresa_id]).includes({:productos_empresa => :empresa}, :estatus, :tipo_gtin).order("producto.fecha_creacion") 
                    render '/productos/retirar_productos.xlsx.axlsx'
                  elsif params[:retirados]
                    @productos = Producto.where("productos_empresa.prefijo = ? and estatus.descripcion like ? and estatus.alcance like ?",params[:empresa_id], 'Retirado', 'Producto').includes({:productos_empresa => :empresa}, :estatus, :tipo_gtin, {:productos_retirados => :sub_estatus}, {:productos_retirados => :motivo_retiro})
                    render '/productos/productos_retirados.xlsx.axlsx'
                  elsif params[:eliminar]
                    @productos = Producto.where("productos_empresa.prefijo = ? and estatus.descripcion like ? and estatus.alcance like ?",params[:empresa_id], 'Retirado', 'Producto').includes({:productos_empresa => :empresa}, :estatus, :tipo_gtin, {:productos_retirados => :sub_estatus}, {:productos_retirados => :motivo_retiro})
                    render '/productos/eliminar_productos.xlsx.axlsx'
                  elsif params[:eliminados]
                    @productos = ProductoEliminado.where("productos_empresa.prefijo = ? and estatus.descripcion like ? and estatus.alcance like ?", params[:empresa_id], 'Eliminado', 'Producto').includes(:estatus, :tipo_gtin, {:producto_elim_detalle => :sub_estatus}, {:producto_elim_detalle => :motivo_retiro}, {:productos_empresa => :empresa})
                    render '/productos/productos_eliminados.xlsx.axlsx'
                  else
                    @productos = Producto.where("productos_empresa.prefijo = ? and estatus.descripcion = ?", params[:empresa_id], 'Activo').includes({:productos_empresa => :empresa}, :estatus, :tipo_gtin).order("producto.fecha_creacion") 
                    render '/productos/index.xlsx.axlsx'
                  end
      }
      
    end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @producto = Producto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/new
  # GET /productos/new.json
  def new
    

    @empresa =  Empresa.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]] )
    @producto = @empresa.producto.build  # Se crea el form_for
    
    @gtin = params[:gtin] if params[:gtin] != ''# SI esta gtin  es para crear gtin tipo 14 base 8 o gtin 14 base 13

    @producto_ = Producto.find(:first, :conditions => ["gtin like ?", params[:gtin]]) if params[:gtin]
    @base = TipoGtin.find(:first, :conditions =>["tipo like ? and base like ?", "GTIN-14", @producto_.tipo_gtin.tipo]) if @producto_


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/1/edit
  def edit
    @empresa = Empresa.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]])
    @producto = Producto.find(:first, :conditions => ["gtin like ?", params[:id]])

  end

  # POST /productos
  # POST /productos.json
  def create

    @empresa = Empresa.find(:first, :conditions => ["prefijo = ?", params[:empresa_id]])

    @gtin = params[:gtin]  if params[:gtin] != ''

    #Producto.crear_gtin(params[:producto][:id_tipo_gtin], params[:empresa_id], params[:gtin], params[:producto][:codigo_prod])
    params[:producto][:gtin] = Producto.crear_gtin(params[:producto][:id_tipo_gtin], params[:empresa_id], params[:gtin], params[:producto][:codigo_prod])
    params[:producto][:fecha_creacion] = Time.now
    estatus = Estatus.find(:first, :conditions => ["(descripcion = ?) and (alcance = ?)", "Activo", "Producto"])
    params[:producto][:id_estatus] = estatus.id
    
    params[:producto][:codigo_prod] = params[:producto][:gtin][7..11] if params[:producto][:id_tipo_gtin] == '3'
    params[:producto][:codigo_prod] = params[:producto][:gtin][3..6] if params[:producto][:id_tipo_gtin] == '1'
    params[:producto][:codigo_prod] = params[:producto][:gtin][9..12] if params[:producto][:id_tipo_gtin] == '4' 
    params[:producto][:codigo_prod] = params[:producto][:gtin][8..12] if params[:producto][:id_tipo_gtin] == '6'


    @producto = Producto.new(params[:producto])

    respond_to do |format|
      if @producto.save

app/views/productos/_exportar_productos_eliminados.html.haml
%table.margen_superior
    %tr
        %td
            %form{action: "#{empresa_productos_path}.pdf", method: "get", target: "_blank"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_eliminados{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos Eliminados formato PDF"}
                    %span.ui-icon.ui-icon-disk
                    Exportar PDF

        %td
            %form{action: "#{empresa_productos_path}.xlsx", method: "get"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_eliminados{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos Eliminados a formato Excel"}
                    %span.ui-icon.ui-icon-disk
                    Exportar Excel

app/views/productos/_exportar_productos_eliminar.html.haml
%table.margen_superior
    %tr
        %td
            %form{action: "#{empresa_productos_path}.pdf", method: "get", target: "_blank"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_eliminar{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos a formato PDF"}
                    %span.ui-icon.ui-icon-disk
                    Exportar PDF

        %td
            %form{action: "#{empresa_productos_path}.xlsx", method: "get"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_eliminar{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos a formato Excel"}
                    %span.ui-icon.ui-icon-disk
                    Exportar Excel

app/views/productos/_exportar_productos_retirados.html.haml
%table
    %tr
        %td
            %form{action: "#{empresa_productos_path}.pdf", method: "get", target: "_blank"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_retirados{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos a formato PDF"}
                    %span.ui-icon.ui-icon-disk
                    Exportar PDF

        %td
            %form{action: "#{empresa_productos_path}.xlsx", method: "get"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_retirados{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos a formato Excel"}
                    %span.ui-icon.ui-icon-disk
                    Exportar Excel
       

app/views/productos/_exportar_productos_retirar.html.haml
%table
    %tr
        %td
            %form{action: "#{empresa_productos_path}.pdf", method: "get", target: "_blank"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_retirar{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos a formato PDF"}
                    %span.ui-icon.ui-icon-disk
                    Exportar PDF

        %td
            %form{action: "#{empresa_productos_path}.xlsx", method: "get"}
                .parametros
                %button.ui-state-default.ui-corner-all.exportar_productos_retirar{:type => "submit", :title => "Opción que te permite exportar el listado general de Productos a formato Excel"}
                    %span.ui-icon.ui-icon-disk
                    Exportar Excel
       

app/views/productos/_footer.html.haml
%tr
	%th
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th
	%th
	
	%th
	

app/views/productos/_footer_eliminar_productos.html.haml
%tr
	%th
	%th
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th
	

app/views/productos/_footer_retirar_productos.html.haml
%tr
	%th
	%th
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th
	%th.ui-state-default{:colspan => "1", :rowspan => "1"}
		%span.filter_column.filter_text
			%input.search_init.text_filter{:type => "text"}/
	%th
	%th
	%th
	

app/views/productos/_form.html.haml
%section.contexto
  %label.contexto 
    =@producto.new_record? ? (@empresa.nombre_empresa + " > Registrar Producto") : (@empresa.nombre_empresa + " > Editar Producto")
  %hr.contexto{:size => "1"}

  %section.formulario
    
    = form_for [@empresa, @producto] do |f|
      - if @producto.errors.any?
        #error_explanation
          %h2= "#{pluralize(@producto.errors.count, "errore")} "
          %ul
            - @producto.errors.full_messages.each do |msg|
              -if msg == 'El codigo de Producto que esta ingresando ya  se encuentra asociado a un GTIN'
                %li="El codigo de Producto que está ingresando ya se encuentra asociado a un GTIN"
              -else
                %li=msg 
      
      %table
        %tr
          %td.texto_tipo_gtin
            =@gtin.nil? ? "Tipo GTIN" : "Tipo GTIN Base"
          %td.combo_tipo_gtin

            -if @producto.new_record?
              =@gtin.nil? ? f.collection_select(:id_tipo_gtin, TipoGtin.find(:all, :conditions => ["tipo in (?)", ["GTIN-8", "GTIN-13"]]), :id, :tipo, :prompt => "-Seleccione-") : f.collection_select(:id_tipo_gtin, TipoGtin.find(:all, :conditions => ["id = ?", params[:base]]), :id, :tipo_gtin_base)

            -else
              =f.hidden_field :id_tipo_gtin, :value => "#{@producto.id_tipo_gtin}"
              =text_field_tag "tipo_gtin", "#{@producto.tipo_gtin.tipo}", :class => "campo_readonly", :readonly => :true
        %tr
          %td.texto_manual_automatico
          %td.radio_manual_automatico
      
        %tr
          %td
            Descripción
          %td
            =params[:descripcion] ? f.text_field(:descripcion, :value => params[:descripcion]) : f.text_field(:descripcion, :autocomplete => "off")
            
        %tr
          %td
            Marca
          %td
            =params[:marca] ? f.text_field(:marca, :value => params[:marca]): f.text_field(:marca, :autocomplete => "off")
        / %tr
        /   %td
        /     GPC
        /   %td
        /     -if @producto.new_record?
        /       -if params[:gpc]
        /         =f.text_field :gpc, :value => params[:gpc], :autocomplete => "off"
        /       -else
        /         =f.text_field :gpc, :autocomplete => "off"
        /     -else
        /       =f.text_field :gpc, :readonly => :true, :class => "campo_readonly"
        %tr
          %td.codigo_producto
            -if !@producto.new_record? or (@producto.errors.messages[:gtin])
              Código Producto
          %td.valor_codigo_producto
            -if !@producto.new_record?
              =(f.text_field :codigo_prod, :readonly => :true, :class => "campo_readonly")
            -elsif @producto.errors.messages[:gtin]
              =f.text_field :codigo_prod
        
      =hidden_field_tag "gtin", "#{@gtin}"
     
      %button#submit.ui-state-default.ui-corner-all.guardar_producto{:type => "submit", :title => "Guardar producto"}
        %span.ui-icon.ui-icon-disk
        Guardar Producto

      %a.ui-state-default.ui-corner-all.regresar{:href => "/empresas/#{params[:empresa_id]}/productos", :title => "Regrar al listado de Productos para esta Empresa"}
        %span.ui-icon.ui-icon-arrowreturnthick-1-w
        Regresar
        
        
      

app/views/productos/_importar_producto.html.haml
.importar_producto
    =form_tag "#{empresa_productos_path}/import" , multipart: true, :id=> "importar_archivo" do
        %table
            %tr
                %td
                    =file_field_tag :file, :id => "archivo_excel"
        %table
            %tr
                %td
                    Tipo GTIN
                %td
                    =select_tag "tipo_gtin", options_from_collection_for_select(TipoGtin.find(:all, :conditions => ["id in (?)", [3,4,6]]), "id", "tipo_gtin_base"), prompt: "- Seleccione -"
            %tr
                %td
                    =submit_tag "Importar", :id => "importar_archivo"
                %td

app/views/productos/edit.html.haml
= render 'form'

app/views/productos/new.html.haml
= render 'form'

app/views/productos/productos_eliminados.html.haml
%section.contexto
    %label.contexto
        =@navegabilidad 
    %hr.contexto{:size => "1"}

%section#areaTrabajo.areaTrabajo
    %p#notice= notice
    = render 'exportar_productos_eliminados'
    %table#data_table_productos_eliminados.display{:"data-source" => "#{empresa_productos_path}.json?eliminados=true"}
        %thead
            %tr
               
                %th Empresa
                %th Tipo GTIN    
                %th GTIN
                %th Descripción
                %th Marca
                %th Estatus
                %th Código Prod
                %th Fecha Creación
                %th Fecha Eliminación
                %th SubEstatus
                %th Motivo Retiro
                
               
        %tbody
        %tfoot
            =render 'footer_productos_eliminados'
    %br/
    %br/
    -if params[:empresas_eliminadas]
        %a.ui-state-default.ui-corner-all.regresar{:href => "/empresas?eliminadas=true", :title => "Regresar al listado de productos para esta Empresa"}
            %span.ui-icon.ui-icon-arrowreturnthick-1-w
            Regresar
    -else
        %a.ui-state-default.ui-corner-all.regresar{:href => "#{empresa_productos_path}", :title => "Regresar al listado de productos para esta Empresa"}
            %span.ui-icon.ui-icon-arrowreturnthick-1-w
            Regresar
   

app/views/productos/retirar_productos.html.haml
%section.contexto
    %label.contexto
        =@navegabilidad 
    %hr.contexto{:size => "1"}

%section#areaTrabajo.areaTrabajo
    %p#notice= notice
    
    = render 'exportar_productos_retirar.html.haml'
    =form_tag "#{empresa_productos_path}/update_multiple", :method => "put", :id => "formulario_retirar_productos" do
       
        %table.margen_inferior{:border => 1}
            %tr
                %td
                    Retiro Masivo
                %td
                    SubEstatus
                %td
                    Motivo Retiro
            %tr
                %td
                    =check_box_tag "retiro_masivo_productos"
                %td
                    =select_tag("retirar_producto_sub_estatus", options_from_collection_for_select(SubEstatus.all, "id", "descripcion"))
                %td
                    =select_tag("retirar_producto_motivo_retiro", options_from_collection_for_select(MotivoRetiro.all, "id", "descripcion"))
        
        
        %table#data_table_retirar_productos.display{:"data-source" => "#{empresa_productos_path}.json?retirar=true"}
            %thead
                %tr
                    %th
                    %th Empresa
                    %th Tipo GTIN    
                    %th GTIN
                    %th Descripción
                    %th Marca
                    %th Estatus
                    %th Código Prod
                    %th Fecha Creación
                    %th SubEstatus
                    %th Motivo Ret
                   
            %tbody
            %tfoot
                =render 'footer_retirar_productos'
        
        %br/
        %br/
        #datos_productos_retirar_productos
        =hidden_field_tag "retirar"
        %button#submit.ui-state-default.ui-corner-all.retirar_productos{:type => "submit", :title => "Retirar Productos"}
            %span.ui-icon.ui-icon-circle-minus
            Retirar
        %a.ui-state-default.ui-corner-all.regresar{:href => "/empresas/#{params[:empresa_id]}/productos", :title => "Regresar al listado de productos para esta Empresa"}
            %span.ui-icon.ui-icon-arrowreturnthick-1-w
            Regresar

        

app/views/productos/show.html.haml
%section.contexto
  %label.contexto 
    -if @producto.new_record?
      Registar Producto 
    -else
      Editar Producto
  %hr.contexto{:size => "1"}

  %section.formulario

  %p#notice= notice

  %table
    %tr
      %td
        
  %p
    %b Gtin:
    = @producto.gtin
  %p
    %b Descripcion:
    = @producto.descripcion
  %p
    %b Marca:
    = @producto.marca
  %p
    %b Gpc:
    = @producto.gpc
  %p
    %b Id estatus:
    = @producto.id_estatus
  %p
    %b Codigo prod:
    = @producto.codigo_prod
  %p
    %b Fecha creacion:
    = @producto.fecha_creacion
  %p
    %b Id tipo gtin:
    = @producto.id_tipo_gtin

  = link_to 'Editar', edit_producto_path(@producto)
  \|
  = link_to 'Productos', productos_path