config/routes.rb
GS1::Application.routes.draw do
  
  get "gerencia/index"
  get "cargo/index"
  get "perfil/index"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :usuarios 

  resources :productos do #/empresas/1/productos

      collection do
        put 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
      end
    end

  
  
  resources :glns do
      collection do
        delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
      end

  end

  resources :empresas do  

    resources :empresa_servicios
    resources :etiquetas do
      collection do
        get 'exportar', :action => 'exportar', :as => 'exportar' 
      end
    end
    
    resources :productos do #/empresas/1/productos

      collection do
        put 'update_multiple', :action => 'update_multiple', :as => 'update_multiple'  # la ruta update_multiple para productos
        post 'import', :action => 'import', :as => 'import'  # Ruta para importar archivos
        
      end
    end

    resources :glns do
      collection do
        delete 'destroy_multiple', :action => 'destroy_multiple', :as => 'destroy_multiple'  # la ruta delete_multiple para gln
      end

    end

    resources :datos_contactos   #/empresas/1/datos_contactos
    
    collection do
      put 'update_multiple', :action => 'update_multiple', :as => 'update_multiple' # La ruta update_multiple para empresas
    end
  end
  
 
  resources :ciudades
  resources :clasificaciones
  resources :municipios
  resources :sessions

  root :to => 'sessions#new'

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  self.table_name = "usuario_interno" # nombre de la tabla asociadoa en el sistema administrativo
  attr_accessible :email, :fecha_creacion, :id_cargo, :id_gerencia, :id_perfil, :password, :password_salt,  :nombre_apellido, :username, :password_confirmation
  validates :email, :username,  :nombre_apellido, :password, :password_confirmation,  :presence => {:message => "No puede estar en blanco"}
  #validates :password,  :presence => {:message => "No puede estar en blanco"}, :on => :create
  validates :password,  :confirmation => true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  before_save :encriptar_password
  belongs_to :perfil, :foreign_key => "id_perfil"
  belongs_to :cargo, :foreign_key => "id_cargo"
  belongs_to :gerencia, :foreign_key => "id_gerencia"

  def self.authenticate(usuario, password)
    user = find_by_username(usuario)
    
    if user && user.password == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encriptar_password
  	if password.present?
  		self.password_salt = BCrypt::Engine.generate_salt  # Semilla aletaoria
  		self.password = BCrypt::Engine.hash_secret(password, password_salt)

  		
  	end
  end
  
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_filter :require_authentication
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    
    params[:usuario][:fecha_creacion] = Time.now
    @usuario = Usuario.new(params[:usuario])

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuarios_path, notice: "Usuario #{@usuario.username} creado correctamente"}
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    #params[:usuario][:password] = nil if params[:usuario][:password] == 'password'

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: "Usuario #{@usuario.username} modificado correctamente" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.haml
%section.contexto
  %label.contexto 
    -if @usuario.new_record?
      Crear Usuario
    -else
      Editar Usuario
  %hr.contexto{:size => "1"}

  %section.formulario
    = form_for(@usuario) do |f|
      - if @usuario.errors.any?
        #error_explanation
          %h2
            = pluralize(@usuario.errors.count, "errore")
          %ul
            - @usuario.errors.full_messages.each do |msg|
              %li= msg
      %table
        %tr
          %td
            Usuario
          %td
            = f.text_field :username
        %tr
          %td
            Clave
          %td
            /=@usuario.new_record? ? f.password_field(:password) : f.password_field(:password, :value => "password")
            =f.password_field(:password)
        %tr
          %td
            Confirmación Clave
          %td
            /=@usuario.new_record? ? f.password_field(:password_confirmation): f.password_field(:password_confirmation, :value => "password")
            =f.password_field(:password_confirmation)
        %tr
          %td
            Nombre
          %td
            =f.text_field :nombre_apellido
        %tr
          %td
            Correo
          %td
            = f.text_field :email
        %tr
          %td
            Perfil
          %td
            =f.collection_select :id_perfil, Perfil.order("descripcion asc"), :id, :descripcion, :prompt => "-Seleccione-"
        %tr
          %td
            Gerencia
          %td
            = f.collection_select :id_gerencia, Gerencia.order("nombre asc"), :id, :nombre, :prompt => "-Seleccione-"
        %tr
          %td
            Cargo
          %td
            = f.collection_select :id_cargo, Cargo.order("descripcion asc"), :id, :descripcion, :prompt => "-Seleccione-"

      .actions
        %button#submit.ui-state-default.ui-corner-all.crear_empresa{:type => "submit", :title => "Guardar usuario"}
          %span.ui-icon.ui-icon-disk
          Guardar

        %a.ui-state-default.ui-corner-all.nuevo_contacto{:href => "#{usuarios_path}", :title => "Regresar al listado de usuarios"}
          %span.ui-icon.ui-icon-arrowreturnthick-1-w
          Regresar
        
        

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.haml
%section.contexto
	%label.contexto Usuarios > Listado
	%hr.contexto{:size => "1"}
%section#areaTrabajo.areaTrabajo
	%p#notice= notice
	%table#usuarios.display
		%thead
			%tr
			%th Usuario
			%th Nombre 
			%th Email
			%th Perfil
			%th Gerencia
			%th Cargo
			%th Fecha Creación
			
			- if UsuariosAlcance.verificar_alcance(session[:perfil], 'Modificar Usuario')
				%th
			- if UsuariosAlcance.verificar_alcance(session[:perfil], 'Eliminar Usuario')
				%th
			
		%tbody
			- @usuarios.each do |usuario|
				%tr
					%td= usuario.username
					%td= usuario.nombre_apellido
					%td= usuario.email
					%td= usuario.try(:perfil).try(:descripcion)
					%td= usuario.try(:gerencia).try(:nombre)
					%td= usuario.try(:cargo).try(:descripcion)
					%td
						= usuario.fecha_creacion.strftime("%Y-%m-%d") if usuario.fecha_creacion
					
					- if UsuariosAlcance.verificar_alcance(session[:perfil], 'Modificar Usuario')
						%td= link_to(( content_tag(:span, '',:class => 'ui-icon ui-icon-extlink')+'Editar').html_safe,  edit_usuario_path(usuario),  {:class => "ui-state-default ui-corner-all botones_servicio", :title => "Editar usuario #{usuario.username}"})
					- if UsuariosAlcance.verificar_alcance(session[:perfil], 'Eliminar Usuario')
						%td= link_to(( content_tag(:span, '',:class => 'ui-icon ui-icon-extlink')+'Eliminar').html_safe,  usuario, method: :delete, data: { confirm: 'Desea ELIMINAR este usuario?'}, :class => "ui-state-default ui-corner-all botones_servicio", :title => "Eliminar usuario #{usuario.username}")

	- if UsuariosAlcance.verificar_alcance(session[:perfil], 'Registrar Usuario')
		%br
		%br

		%a.ui-state-default.ui-corner-all.regresar_empresas_sin_espacio{:href => "#{new_usuario_path}", :title => "Crear usuario"}
			%span.ui-icon.ui-icon.ui-icon-circle-plus
			Crear usuario
		%a.ui-state-default.ui-corner-all.regresar_empresas{:href => "/empresas", :title => "Regresar listado general de empresas"}
			%span.ui-icon.ui-icon.ui-icon-circle-plus
			Regresar

		

	
	

app/views/usuarios/login.html.haml
%section.contexto
  %label.contexto 
    -if @empresa.new_record?
      Registar Empresa - Datos Básicos
    -else
      Editar Empresa - Datos Básicos
  %hr.contexto{:size => "1"}

  %section.formulario
    = form_for(@usuario) do |f|
      - if @usuario.errors.any?
        #error_explanation
          %h2
            = pluralize(@usuario.errors.count, "error")
          %ul
            - @usuario.errors.full_messages.each do |msg|
              %li= msg
      %table
        %tr
          %td
            Usuario
          %td
            = f.text_field :username
        %tr
          %td
            Clave
          %td
            = f.password_field :password
        %tr
          %td
            Confirmación
          %td
            = f.password_field :password_confirmation
      .actions
        = f.submit

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.haml
%section.contexto
  %label.contexto Usuarios > Detalle
  %hr.contexto{:size => "1"}
%section#areaTrabajo.areaTrabajo{:style => "font: 100% 'Trebuchet MS', sans-serif"}
  %p#notice= notice
  %table
    %tr
      %td
        Usuario
      %td
        = @usuario.username
    %tr
      %td
        Nombre 
      %td
        = @usuario.nombre_apellido
    %tr
      %td
        Correo
      %td
        = @usuario.email
    %tr
      %td
        Perfil
      %td
        = @usuario.perfil.descripcion
    %tr
      %td
        Gerencia
      %td
        = @usuario.gerencia.nombre
    %tr
      %td
        Cargo
      %td
        = @usuario.cargo.descripcion
    %tr
      %td
        Fecha Creación
      %td
        = @usuario.fecha_creacion.strftime("%Y-%m-%d")
  %br
  %br

  - if UsuariosAlcance.verificar_alcance(session[:perfil], 'Modificar Usuario')
    /=link_to(( content_tag(:span, '',:class => 'ui-icon ui-icon-extlink')+'Detalle').html_safe, empresa_path(empresa),  {:class => "ui-state-default ui-corner-all botones_servicio", :title => "Detalle de la empresa #{empresa.nombre_empresa}"}),        
    = link_to(( content_tag(:span, '',:class => 'ui-icon ui-icon-extlink')+'Editar').html_safe,  edit_usuario_path(@usuario), :class => "editar_usuario ui-state-default ui-corner-all" )
  = link_to(( content_tag(:span, '',:class => 'ui-icon ui-icon-extlink')+'Regresar').html_safe,  usuarios_path, :class => "editar_usuario ui-state-default ui-corner-all")